Update patch set 2
Patch Set 2: Verified-1

Building this change (and its parent or current master) fails for me locally, this way; what am I missing?:

$ bazel build go-import
ERROR: .../.cache/bazel/_bazel_.../2c77223b9448ac8dfd0e4fedc7511dde/external/com_googlesource_gerrit_bazlets/gerrit_api_maven_local.bzl:37:3: no such package '@gerrit_plugin_api//jar': failed /usr/bin/python .../.cache/bazel/_bazel_.../2c77223b9448ac8dfd0e4fedc7511dde/external/com_googlesource_gerrit_bazlets/tools/download_file.py -o .../.cache/bazel/_bazel_.../2c77223b9448ac8dfd0e4fedc7511dde/external/gerrit_plugin_api/jar/gerrit-plugin-api-2.16-SNAPSHOT.jar -u MAVEN_LOCAL:/com/google/gerrit/gerrit-plugin-api/2.16-SNAPSHOT/gerrit-plugin-api-2.16-SNAPSHOT.jar: Download file://.../.m2/repository/com/google/gerrit/gerrit-plugin-api/2.16-SNAPSHOT/gerrit-plugin-api-2.16-SNAPSHOT.jar
error using curl: Command '['curl', '--proxy-anyauth', '-ksfo', '.../.gerritcodereview/bazel-cache/downloaded-artifacts/gerrit-plugin-api-2.16-SNAPSHOT.jar-a6cf043c8712b39b43739ffe82e53a1923b81630', 'file://.../.m2/repository/com/google/gerrit/gerrit-plugin-api/2.16-SNAPSHOT/gerrit-plugin-api-2.16-SNAPSHOT.jar']' returned non-zero exit status 37
 and referenced by '//external:gerrit-plugin-api-neverlink'
ERROR: Analysis of target '//:go-import' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.294s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading: @embedded_jdk// ... (2 packages)

Patch-set: 2
Reviewer: Gerrit User 1012732 <1012732@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1